### ISSUE TITLE
List of things that could be improved. 

### ISSUE THREAD

**Issue by rickardd** [SomarDesignStudios/application-menu#2]
- js-prefix all classes to seperate javascript from styles. e.g js-application-menu
- Update the example with a ul-list with two application-menus
- Add roles to the ul-lists e.g role='menubar/menuitem' 
- Remove build tooling. It's hard to make necessary changes on the fly without installing npm packages and such. 
- Constructor could take a few arguments e.g 
1 close-on-document-click(true/false)
2 css-class-name. To avoid conflicts between menus an option to change the selector class name would be good.

**Comment by flashbackzoo** [comment]
Thanks Rick!

I'll close this. I've created a seperate issue for each item you raised.
